### ISSUE TITLE
Compatibility issue with go 1.16

### ISSUE THREAD

**Issue by czekan** [iromli/go-itsdangerous#2]
Signing message on go version 1.16 makes crypto/hmac  lib panic

```
package main

import (
        "log"

        itsdangerous "github.com/iromli/go-itsdangerous"
)

func main() {
        secret := "seeecret"
        msg := "6858"
        signature := itsdangerous.NewSignature(secret, "", "", "", nil, nil)
        signed_msg, _ := signature.Sign(msg)
        log.Println(signed_msg)
}
```

```
panic: crypto/hmac: hash generation function does not produce unique values

goroutine 1 [running]:
crypto/hmac.New(0xc000068e28, 0xc000014048, 0x14, 0x18, 0x14, 0x18)
	/usr/local/go-faketime/src/crypto/hmac/hmac.go:143 +0x370
github.com/iromli/go-itsdangerous.(*HMACAlgorithm).GetSignature(0xc000010280, 0xc000014030, 0x14, 0x4ce4e6, 0x4, 0x7f346845a108, 0x60, 0xc000056180)
	/tmp/gopath230749032/pkg/mod/github.com/iromli/go-itsdangerous@v0.0.0-20190903235033-828af6836b4f/algorithm.go:23 +0xa5
github.com/iromli/go-itsdangerous.(*Signature).Get(0xc000056180, 0x4ce4e6, 0x4, 0x100000000000001, 0xc000056180, 0xc000068ef0, 0x4a7b0d)
	/tmp/gopath230749032/pkg/mod/github.com/iromli/go-itsdangerous@v0.0.0-20190903235033-828af6836b4f/signature.go:68 +0x99
github.com/iromli/go-itsdangerous.(*Signature).Sign(0xc000056180, 0x4ce4e6, 0x4, 0x13, 0x4ce3a7, 0x1, 0x4cf946)
	/tmp/gopath230749032/pkg/mod/github.com/iromli/go-itsdangerous@v0.0.0-20190903235033-828af6836b4f/signature.go:88 +0x45
main.main()
	/tmp/sandbox285037293/prog.go:13 +0x79

Program exited: status 2.
```

**Comment by Rogalek** [comment]
I have the same issue with the newest go.
